version: '3'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: gal
      POSTGRES_PASSWORD: lag
      POSTGRES_DB: db
    ports:
      - 8080:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db: ~
